### PR TITLE
Add Bitbucket Cloud auth type

### PR DESCRIPTION
**Pull request by nexdrew**
Assumes bump of npm-auth-ws Docker image to version 2.1.0 (to install module version 3.1.0).

Here's a preview of the admin UI additions:
screen shot 2016-03-02 at 5 03 36 pm

screen shot 2016-03-02 at 4 23 04 pm

### CODE REVIEW

**Comment by nexdrew** [comment]
Released to Unstable channel as version 5f3444f (260)

**Comment by nexdrew** [comment]
Rebased, updated, and released to Unstable channel as version `bea7112 (292)`.

**Comment by nexdrew** [comment]
Testing discovered that `@npm/npmo-auth-bitbucket@0.1.1` is incompatible with website login since email is required. Will need to update the auth plugin to use username as email when email is not provided.

**Comment by bcoe** [comment]
:shipit: I'd love to write a follow up blog post, perhaps we can do this next week.

**Pull request merged**
