### PR TITLE
feat: bitbucket support for website login, better named github tokens

### PR DESCRIPTION
**Pull request by nexdrew**
Update npm-auth-ws to pull in [`@npm/npme-auth-bitbucket@1.0.0`](https://github.com/npm/npme-auth-bitbucket/compare/v0.1.1...v1.0.0) and [`@npm/npme-auth-github@1.4.0`](https://github.com/npm/npme-auth-github/compare/v1.3.0...v1.4.0)

### CODE REVIEW

**Comment by nexdrew** [comment]
Verified Bitbucket auth works with website login now, as long as you use your email address as the username.

**Comment by bcoe** [comment]
@nexdrew 👍 

I like the convention of using the `candidate` suffix.

**Comment by nexdrew** [comment]
I like that it makes a Docker image look less official during testing, but I'm not crazy about it. The bad part is, once a `candidate` is successfully tested, I have to change the version and cut a new release. The good part is that I know non-`candidate`s are fully tested and are safe to push to Docker Hub. (I only push `candidate`s to Replicated for testing.)

At any rate, I verified the GitHub changes still work and use a new token name, which is a silly cosmetic change, I know, but looks more consistent with our brand name.

I will promote the candidate, re-release, and merge.

**Comment by nexdrew** [comment]
Released to Unstable and Beta channels as version `a00d600 (296)`

**Pull request merged**
